task2
sergey-berezin/409_doronin pull request #2
Opened 2024-09-30 16:29 UTC by Shirlineyn

1. Асинхронные реализации Crossover и SelectBySort оказались хуже синхронных (причем раза в 4 по какой-то причине. Random.Shared как кандидата на bottleneck рассмотрел, вроде бы не он), поэтому в WPF из асинхронных только Mutate.
2. шарики можно таскать, спасибо [этому замечательному человеку](https://www.codeproject.com/Articles/15354/Dragging-Elements-in-a-Canvas)

2024-10-02 13:55 UTC, sergey-berezin commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +                tasks[i] = Task.Factory.StartNew(() =>
Выглядит как хороший кандидат для Parallel.For

2024-10-02 13:55 UTC, sergey-berezin commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +                if (task.IsCompleted)
Зачем проверять на IsCompleted?

2024-10-02 13:55 UTC, sergey-berezin commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +                tasks[i] = Task.Factory.StartNew(() =>
Parallel.For

2024-10-07 16:02 UTC, Shirlineyn commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +                tasks[i] = Task.Factory.StartNew(() =>
И правда хороший
![image](https://github.com/user-attachments/assets/a127935e-30cf-4401-a84d-93c943ad6f3a)

2024-10-07 16:02 UTC, Shirlineyn commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +                tasks[i] = Task.Factory.StartNew(() =>
![image](https://github.com/user-attachments/assets/76156185-4f4a-4d17-8422-bf3f7d67450b)
![image](https://github.com/user-attachments/assets/593047ff-6636-4876-a60b-e0f0e8a414ba)

снимаю шляпу.

2024-10-07 16:16 UTC, Shirlineyn commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +                if (task.IsCompleted)
выпилено вместе с task-ами

2024-10-08 09:57 UTC, sergey-berezin requested changes

2024-10-08 09:57 UTC, sergey-berezin commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +            entities.Sort((e1, e2) => fitMap[e2].CompareTo(fitMap[e1]));
На 20 городах вылетает с исключением:

![image](https://github.com/user-attachments/assets/21f78e9e-009d-46c4-a418-29633ccac3ec)

2024-10-08 09:57 UTC, sergey-berezin commented on genetic_algorithm/genetic_algorithm/genetic_algorithm - Backup.csproj
Зачем нужен backup? git отлично хранит старые версии.

2024-10-08 09:57 UTC, sergey-berezin commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +        public abstract Entity Crossover(ref readonly Entity entity);
Зачем передавать Entity как ref? Класс и так передаётся по ссылке.

2024-10-17 10:36 UTC, Shirlineyn commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +            entities.Sort((e1, e2) => fitMap[e2].CompareTo(fitMap[e1]));
Оказалось, что если удалять элемент в процессе отбора, и одновременнопытаться его напечатать то выйдет ошибочка-с. Пофикшено, до отбора ждем окончания вывода предыдущего поколения.

2024-10-17 10:37 UTC, Shirlineyn commented on genetic_algorithm/genetic_algorithm/genetic_algorithm - Backup.csproj
VS нагенерил :(

2024-10-17 10:39 UTC, Shirlineyn commented on genetic_algorithm/genetic_algorithm/genetic_algorithm.cs
> +        public abstract Entity Crossover(ref readonly Entity entity);
Артефакт отчаянных попыток в оптимизацию, убрал

2024-10-17 10:41 UTC, Shirlineyn commented
Поигрался с оптимизацией алгоритма, оказалось, что если в моей предыдущей реализации задавать высокое значение мутации, то это приводило к тому, что у элементов не было возможности мутировать локально в 1-2 местах. В целом, алгоритм неплохо сходится при значении индекса мутации ~числу точек.

2024-10-17 13:46 UTC, sergey-berezin commented
Задание 2 принято.

2024-10-17 13:46 UTC, merged